### ISSUE TITLE
把apptheme继承制qmui之后提示java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by tx123456** [QMUI/QMUI_Android#10]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 5`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.2.3`
- [x] QMUI Android 版本：`1.0.0`

### 具体问题描述 ###
把apptheme继承制qmui之后出错，改怎么处理
#### 异常日志（堆栈） ####
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.tanxin.qmdemo, PID: 3552
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tanxin.qmdemo/com.tanxin.qmdemo.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                   Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                      at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:359)
                      at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                      at com.tanxin.qmdemo.MainActivity.onCreate(MainActivity.java:11)
                      at android.app.Activity.performCreate(Activity.java:5990)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by chanthuang** [comment]
不要继承 `QMUI`，改为继承 `QMUI.Compat`

**Comment by tx123456** [comment]
还有就是我在使用qmui里面的属性提示找不到资源，这应该怎么办

<com.qmuiteam.qmui.widget.QMUITopBar
        android:layout_width="match_parent"
        android:layout_height="?attr/qmui_topbar_height"/>


catch exception when loading tinker:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yihan.resourcecollect/com.yihan.resourcecollect.module.setting.activity.AboutUsActivity}: java.lang.RuntimeException: Failed to resolve attribute at index 6
                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                              at android.app.ActivityThread.access$800(ActivityThread.java:151)
                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                              at android.os.Handler.dispatchMessage(Handler.java:102)
                              at android.os.Looper.loop(Looper.java:135)
                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                              at java.lang.reflect.Method.invoke(Native Method)
                              at java.lang.reflect.Method.invoke(Method.java:372)
                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                           Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 6
                              at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:603)
                              at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6473)
                              at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6641)
                              at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1864)
                              at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1776)
                              at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:62)
                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                              at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                              at com.yihan.resourcecollect.mvp.base.BaseTitleActivity.setBaseView(BaseTitleActivity.java:35)
                              at com.yihan.resourcecollect.mvp.base.BaseActivity.onCreate(BaseActivity.java:46)
                              at android.app.Activity.performCreate(Activity.java:5990)
                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                              at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                              at android.os.Looper.loop(Looper.java:135) 
                              at android.app.ActivityThread.main(ActivityThread.java:5254) 
                              at java.lang.reflect.Method.invoke(Native Method) 
                              at java.lang.reflect.Method.invoke(Method.java:372) 
                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by cgspine** [comment]
AboutUsActivity 用的 theme 是什么？

**Comment by tx123456** [comment]
新建的项目，哪里来的AboutUsActivity

**Comment by tx123456** [comment]
恩，弄好了，忘记继承apptheme了
