### ISSUE TITLE
QMUIListPopup  崩溃 

### ISSUE THREAD

**Issue by goodluckforme** [QMUI/QMUI_Android#129]
### 运行环境 ###

- [x] 设备型号：如：`vivox9i`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.0.0`
- [x] QMUI Android 版本：`1.0.6'`

### 具体问题描述 ###
弹窗崩溃  显示填充器异常  可是修改后仍然报错
 qMPopupWindow = QMUIListPopup(this@RegisterActivity, QMUIPopup.DIRECTION_NONE, null)
        qMPopupWindow?.create(QMUIDisplayHelper.dp2px(this@RegisterActivity, 250),
                QMUIDisplayHelper.dp2px(this@RegisterActivity, 200),
                null)
#### 异常日志（堆栈） ####
 FATAL EXCEPTION: main
                                                                       Process: banyuekj.com.yiwushop, PID: 24226
                                                                       android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>
                                                                       Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:654)
                                                                           at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                           at android.view.LayoutInflater.onCreateView(LayoutInflater.java:762)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:830)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:903)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:866)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:524)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:432)
                                                                           at com.qmuiteam.qmui.widget.popup.QMUIPopup.setContentView(QMUIPopup.java:245)
                                                                           at com.qmuiteam.qmui.widget.popup.QMUIListPopup.create(QMUIListPopup.java:41)
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity.showSellerPop(RegisterActivity.kt:83)
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity.access$showSellerPop(RegisterActivity.kt:28)
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity$initView$1.doResume(RegisterActivity.kt:62)
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity$initView$1.invoke(RegisterActivity.kt)
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity$initView$1.invoke(RegisterActivity.kt:28)
                                                                           at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285)
                                                                           at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                           at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
                                                                        Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301a7 a=-1}
                                                                           at android.content.res.TypedArray.getDrawable(TypedArray.java:925)
                                                                           at android.view.View.<init>(View.java:4207)
                                                                           at android.view.ViewGroup.<init>(ViewGroup.java:579)
                                                                           at android.widget.FrameLayout.<init>(FrameLayout.java:92)
                                                                           at android.widget.FrameLayout.<init>(FrameLayout.java:87)
                                                                           at android.widget.FrameLayout.<init>(FrameLayout.java:82)
                                                                           at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:654) 
                                                                           at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                           at android.view.LayoutInflater.onCreateView(LayoutInflater.java:762) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:830) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:903) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:866) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:524) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:432) 
                                                                           at com.qmuiteam.qmui.widget.popup.QMUIPopup.setContentView(QMUIPopup.java:245) 
                                                                           at com.qmuiteam.qmui.widget.popup.QMUIListPopup.create(QMUIListPopup.java:41) 
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity.showSellerPop(RegisterActivity.kt:83) 
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity.access$showSellerPop(RegisterActivity.kt:28) 
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity$initView$1.doResume(RegisterActivity.kt:62) 
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity$initView$1.invoke(RegisterActivity.kt) 
                                                                           at banyuekj.com.yiwushop.ui.activity.RegisterActivity$initView$1.invoke(RegisterActivity.kt:28) 
                                                                           at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285) 
                                                                           at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
                                                                           at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171) 
                                                                           at android.os.Handler.handleCallback(Handler.java:751) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6209) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)

**Comment by cgspine** [comment]
没有用 QMUI 的 theme?

**Comment by goodluckforme** [comment]
没有  因为 QmUI的Theme 会修改 状态栏的颜色   这边自己设置 会无效
<item name="colorPrimary">@color/colorPrimary</item>
<item name="colorPrimaryDark">@color/colorPrimaryDark</item>
<item name="colorAccent">@color/colorAccent</item>

**Comment by cgspine** [comment]
如果没有用QMUI的theme，很多组件都不能正常工作的。如果不用沉浸式的话，在values-v21的theme下修改 `<item name="android:colorPrimaryDark">@color/colorPrimaryDark</item>` 即可。 QMUI.Compat 有个bug，错误的重写了`<item name="android:colorPrimaryDark">`，应当重写`<item name="colorPrimaryDark">`。

如果你不想用QMUI 的 Theme， 可参看 [QMUI Q & A](https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A)

**Comment by yangkun19921001** [comment]
![image](https://user-images.githubusercontent.com/20500834/34332653-4c2449fa-e96e-11e7-9448-836cd5470b33.png)
![image](https://user-images.githubusercontent.com/20500834/34332659-5d65d2c4-e96e-11e7-9147-30281af057e4.png)
版本 1.0.6 使用 popup 崩溃 ，我的主题也指向了 文档中要求的主题。

**Comment by cgspine** [comment]
这个崩溃只会是 theme 的原因。是不是你有多个value目录，有遗漏更改？

**Comment by goodluckforme** [comment]
@cgspine   嗯 them 修改好了  只不过自定义属性太多了  我这边自己设置起来还要查看 demo   一个个改

**Comment by yangkun19921001** [comment]
@cgspine 感谢回复，我在看看源代码跟我对比较下 看哪里还需要修改。
