### ISSUE TITLE
mTabSegment.setDefaultNormalColor(normalColor) 控指针···

### ISSUE THREAD

**Issue by goodluckforme** [QMUI/QMUI_Android#130]
### 运行环境 ###

- [x] 设备型号：如：`vivox9i`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.0.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
  val normalColor = QMUIResHelper.getAttrColor(this, R.attr.qmui_config_color_gray_6)
        val selectColor = QMUIResHelper.getAttrColor(this, R.attr.qmui_config_color_blue)
        mTabSegment.setDefaultNormalColor(normalColor)
        mTabSegment.setDefaultSelectedColor(selectColor)
控指针···
真不知道这个怎么搞 点过去也有引用   是不是要在自己的style自己写一遍
#### 异常日志（堆栈） ####
FATAL EXCEPTION: main
                                                                       Process: banyuekj.com.yiwushop, PID: 24130
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void com.qmuiteam.qmui.widget.QMUITabSegment.setDefaultNormalColor(int)' on a null object reference
                                                                           at banyuekj.com.yiwushop.ui.activity.MainActivity.initTabs(MainActivity.kt:61)
                                                                           at banyuekj.com.yiwushop.ui.activity.MainActivity.initData(MainActivity.kt:44)
                                                                           at com.banyue.huiwanjia.ui.base.BaseActivity.onWindowFocusChanged(BaseActivity.kt:75)
                                                                           at android.support.v7.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:123)
                                                                           at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1535)
                                                                           at android.view.View.dispatchWindowFocusChanged(View.java:10300)
                                                                           at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1196)
                                                                           at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3626)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)

**Comment by goodluckforme** [comment]
搞错了···

**Comment by cgspine** [comment]
这不是 mTabSegment 为 null 了吗？
