### ISSUE TITLE
when i  show QMUIPopup on Galaxy Note3 Lite 4G , it crash

### ISSUE THREAD

**Issue by caowen** [QMUI/QMUI_Android#167]
### 运行环境 ###

 设备型号：如： SM-N7508V
 设备系统版本： `Android 4.3
 Gradle 版本：`2.3.0`
 QMUI Android 版本：`1.0.6`

#### 异常日志（堆栈） ####
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NoSuchMethodError: android.view.View.isAttachedToWindow
                      at com.qmuiteam.qmui.widget.popup.QMUIBasePopup.show(QMUIBasePopup.java:116)
                      at com.qmuiteam.qmui.widget.popup.QMUIBasePopup.show(QMUIBasePopup.java:111)
                      at com.anjiahome.housekeeper.ui.SurrenderDetailActivity$initView$3.onClick(SurrenderDetailActivity.kt:123)
                      at android.view.View.performClick(View.java:4476)
                      at com.anjiahome.housekeeper.ui.SurrenderDetailActivity$initView$5.run(SurrenderDetailActivity.kt:135)
                      at android.os.Handler.handleCallback(Handler.java:730)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:177)
                      at android.app.ActivityThread.main(ActivityThread.java:5493)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:525)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by cgspine** [comment]
这手机 rom 的 View 竟然没有方法 isAttachedToWindow ？

**Comment by caowen** [comment]
这个APi 版本好像比较高
