### ISSUE TITLE
永远都是Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>

### ISSUE THREAD

**Issue by ZCKun** [QMUI/QMUI_Android#179]
### 运行环境 ###

- [x] 设备型号：KIW-TL00H
- [x] 设备系统版本：Android 6.0.1
- [x] Gradle 版本：4.1
- [x] QMUI Android 版本：1.0.6

### 具体问题描述 ###
测试了使用 QMUITipDialog、QMUIPopup 运行直接报错：Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
#### 问题截图 ####
![Uploading image.png…]()

#### 异常日志（堆栈） ####
02-04 22:41:03.967 32396-32396/com.kabegay E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.kabegay, PID: 32396
                                                             android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:558)
                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
                                                                 at android.view.LayoutInflater.inflate(<Xposed>)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:434)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                 at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)
                                                                 at android.app.Dialog.setContentView(Dialog.java:543)
                                                                 at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:136)
                                                                 at com.kabegay.MainActivity$4.onClick(MainActivity.java:186)
                                                                 at android.view.View.performClick(View.java:5264)
                                                                 at android.view.View$PerformClick.run(View.java:21297)
                                                                 at android.os.Handler.handleCallback(Handler.java:743)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:150)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
                                                              Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:664)
                                                                 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
                                                                 at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105)
                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:713)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337) 
                                                                 at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:434) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                 at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420) 
                                                                 at android.app.Dialog.setContentView(Dialog.java:543) 
                                                                 at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:136) 
                                                                 at com.kabegay.MainActivity$4.onClick(MainActivity.java:186) 
                                                                 at android.view.View.performClick(View.java:5264) 
                                                                 at android.view.View$PerformClick.run(View.java:21297) 
                                                                 at android.os.Handler.handleCallback(Handler.java:743) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                 at android.os.Looper.loop(Looper.java:150) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103) 
                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:638)
                                                                 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64) 
                                                                 at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105) 
                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:713) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:854) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337) 
                                                                 at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:434) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                 at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420) 
                                                                 at android.app.Dialog.setContentView(Dialog.java:543) 
                                                                 at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:136) 
                                                                 at com.kabegay.MainActivity$4.onClick(MainActivity.java:186) 
                                                                 at android.view.View.performClick(View.java:5264) 
                                                                 at android.view.View$PerformClick.run(View.java:21297) 
                                                                 at android.os.Handler.handleCallback(Handler.java:743) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                 at android.os.Looper.loop(Looper.java:150) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103) 
                                                              Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0401f7 a=3}
                                                                 at android.content.res.TypedArray.getDrawable(TypedArray.java:909)
                                                                 at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1372)
                                                                 at android.view.View.<init>(View.java:3999)
                                                                 at android.view.ViewGroup.<init>(ViewGroup.java:573)
                                                                 at android.widget.LinearLayout.<init>(LinearLayout.java:206)
                                                                 at android.widget.LinearLayout.<init>(LinearLayout.java:202)
                                                                 at android.widget.LinearLayout.<init>(LinearLayout.java:198)
                                                                 at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:638) 
                                                                 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64) 
                                                                 at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105) 
                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:713) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:781) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:854) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337) 
                                                                 at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:434) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                 at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420) 
                                                                 at android.app.Dialog.setContentView(Dialog.java:543) 
                                                                 at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:136) 
                                                                 at com.kabegay.MainActivity$4.onClick(MainActivity.java:186) 
                                                                 at android.view.View.performClick(View.java:5264) 
                                                                 at android.view.View$PerformClick.run(View.java:21297) 
                                                                 at android.os.Handler.handleCallback(Handler.java:743) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                 at android.os.Looper.loop(Looper.java:150) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)

**Comment by cgspine** [comment]
没有用 QMUI 提供的 theme?

**Comment by woodensheep** [comment]
dialogActivity怎么使用 QMUI 提供的 theme? 
   例：<style name="TipDialog" parent="@android:style/Theme.Holo.Light.Dialog">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowCloseOnTouchOutside">false</item>
        <item name="android:windowBackground">@android:color/transparent</item>
    </style>
使用mui控件的时候也会报这个错误

**Comment by cgspine** [comment]
activity 要使用 QMUI.Compat, Dialog可以使用 QMUI.Dialog 这个theme。 你的 dialogActivity 是一个 activity 包含 一个 dialog 吧

**Comment by wukuiqing49** [comment]
一个activity 包含两个个fragment      fragment 列表的条目点击事件 点击弹出 QMUITipDialog   然而是这个报错来着   顿时很懵逼这是什么原因报布局错误

**Comment by cgspine** [comment]
这一般都是 activity 的 theme 错误吧

**Comment by xwysun** [comment]
同样的错误 有解决方案吗

**Comment by longzekai** [comment]
我也是一开始老是报这个错，幸好想到了到这里看issues

**Comment by manqianzhuang** [comment]
只要在activity中调用QMUIWindowInsetLayout以及他的子件就会崩掉，报上面的错误。问题没有解决啊

**Comment by cgspine** [comment]
你 activity 的 theme 是什么？
