### ISSUE TITLE
QMUIBottomSheet 运行闪退

### ISSUE THREAD

**Issue by TTHHR** [QMUI/QMUI_Android#185]
### 运行环境 ###

- [x] 设备型号：如：`华为C199`
- [x] 设备系统版本：如 `Android 4.4`
- [x] Gradle 版本：如 3.2.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
只是个测试，但是失败了

样式
    <style name="AppTheme" parent="QMUI.Compat">
    </style>
使用
 override fun onStart() {
        showBottomSheetList()

        super.onStart()
    }
    private fun showBottomSheetList() {
       val sheet= QMUIBottomSheet.BottomListSheetBuilder(applicationContext)
                .addItem("dgdgrhd")
                .addItem("dgdggs")
                .addItem("ghjkkkkjkh")
                .setOnSheetItemClickListener { dialog, itemView, position, tag ->
                    dialog.dismiss()
                    when (position) {
                        0 -> {

                        }
                        1 -> {
                        }
                        2 -> {
                        }
                        else -> {
                        }
                    }
                }
                .build()
        sheet.show()
    }
#### 异常日志（堆栈） ####
 java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.qingyuyu.abuot/cn.qingyuyu.abuot.AboutActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2275)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.access$1100(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5291)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:640)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
        at android.view.View.inflate(View.java:17515)
        at com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet$BottomListSheetBuilder.buildViews(QMUIBottomSheet.java:351)
        at com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet$BottomListSheetBuilder.build(QMUIBottomSheet.java:341)
        at cn.qingyuyu.abuot.AboutActivity.showBottomSheetList(AboutActivity.kt:64)
        at cn.qingyuyu.abuot.AboutActivity.onStart(AboutActivity.kt:41)

**Comment by TTHHR** [comment]
applicationContext的问题，改成this就行了
