### ISSUE TITLE
QMUIListPopup Android4.2抛错

### ISSUE THREAD

**Issue by aojiaoqiang** [QMUI/QMUI_Android#211]
### 运行环境 ###

- [x] 设备型号：：`三星SM-G3818`
- [x] 设备系统版本： `Android 4.2.2`
- [x] Gradle 版本： `4.1`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
使用QMUIListPopup组件，调用show（View view）方法抛错，
java.lang.NoSuchMethodError: android.view.View.isAttachedToWindow
找不到这个方法
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/19906041/37697656-01fc491a-2d19-11e8-95e3-d0f4d52160a9.png)

![image](https://user-images.githubusercontent.com/19906041/37697664-1202044e-2d19-11e8-928c-9e2ed763ba20.png)

#### 异常日志（堆栈） ####
AndroidRuntime: FATAL EXCEPTION: main
                                                                              java.lang.NoSuchMethodError: android.view.View.isAttachedToWindow
                                                                                  at com.qmuiteam.qmui.widget.popup.QMUIBasePopup.show(QMUIBasePopup.java:116)
                                                                                  at com.qmuiteam.qmui.widget.popup.QMUIBasePopup.show(QMUIBasePopup.java:111)
                                                                                  at com.gonghuipay.commfacemanager.ui.personnel.PersonnelManagerFragment.showAddPerson(PersonnelManagerFragment.java:80)
                                                                                  at com.gonghuipay.commfacemanager.ui.personnel.PersonnelManagerFragment.onViewClicked(PersonnelManagerFragment.java:55)
                                                                                  at com.gonghuipay.commfacemanager.ui.personnel.PersonnelManagerFragment_ViewBinding$2.doClick(PersonnelManagerFragment_ViewBinding.java:39)
                                                                                  at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                  at android.view.View.performClick(View.java:4439)
                                                                                  at android.view.View$PerformClick.run(View.java:18395)
                                                                                  at android.os.Handler.handleCallback(Handler.java:725)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                  at android.os.Looper.loop(Looper.java:176)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5301)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by cgspine** [comment]
可以升级到1.0.8版本
