### ISSUE TITLE
熄屏返回app，报Fragment 异常，crash,请问可能是啥原因？

### ISSUE THREAD

**Issue by hewking** [QMUI/QMUI_Android#214]
### 运行环境 ###

OS Version: 7.1.1 25
Vendor: OnePlus
Model: ONEPLUS A5000
Device: OnePlus5
Hardware: qcom

CPU ABI: arm64-v8a
CPU ABI 2: 

memoryClass: 256
largeMemoryClass: 512

手机内存大小:5.59 GB

系统总内存:5.59 GB

系统剩余内存:1.05 GB

SD空间大小:52.57 GB

SD可用空间大小:1.20 GB

### 具体问题描述 ###
你好 项目中用的一个Activity 多个 Fragment 的方式,启动QMUIFragment 的时候，有些Fragment调用了 addToBackStack 有些没有 。现在出现当熄屏后，在回到app ，偶现这个问题。可能是啥原因导致的？

#### 异常日志（堆栈） ####
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2055)

	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2078)

	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)

	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)

	at com.qmuiteam.qmui.arch.QMUIFragmentActivity.startFragment(QMUIFragmentActivity.java:76)

	at com.qmuiteam.qmui.arch.QMUIFragmentActivity.startFragment(QMUIFragmentActivity.java:61)

	at com.qmuiteam.qmui.arch.QMUIFragment.startFragment(QMUIFragment.java:100)

	at com.opechain.wallet.base.BaseFragment.startFragment(BaseFragment.kt:37)

	at com.opechain.wallet.base.BaseFragment.onActivityBackToFront(BaseFragment.kt:114)

	at com.opechain.wallet.app.GlobalAppProxy.notifyActivityBackToFront(GlobalAppProxy.kt:33)

	at com.opechain.wallet.app.GlobalActivityLifecycleCallback.onActivityStarted(GlobalActivityLifecycleCallback.kt:42)

	at android.app.Application.dispatchActivityStarted(Application.java:207)

	at android.app.Activity.onStart(Activity.java:1209)

	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:589)

	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)

	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1322)

	at android.app.Activity.performStart(Activity.java:6760)

	at android.app.Activity.performRestart(Activity.java:6834)

	at android.app.ActivityThread.handleSleeping(ActivityThread.java:4209)

	at android.app.ActivityThread.-wrap23(ActivityThread.java)

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)

	at android.os.Handler.dispatchMessage(Handler.java:102)

	at android.os.Looper.loop(Looper.java:154)

	at android.app.ActivityThread.main(ActivityThread.java:6334)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by cgspine** [comment]
`startFragment` 的时机不对，`ActivityLifecycleCallback.onActivityStarted` 是在 `Activity` 的 `onStart` 中调用，fragment 的 状态恢复也是在 `onStart` 中，但是在`ActivityLifecycleCallback.onActivityStarted` 之后调用的。你可以在 `onActivityResumed` 中`startFragment`

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/37904469-707dd8f4-312e-11e8-827a-bd9fe8347ced.png)
根据这篇文章（https://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html）， onStart 和 onResume 都有可能造成 crash。最好是在`FragmentActivity#onResumeFragments()` 或者 `Activity#onPostResume()`处理。所以你可以在 `ActivityLifecycleCallback.onActivityStarted`时在 Activity 中保存一个 Runnable, 然后在 `onResumeFragments`时执行。

**Comment by hewking** [comment]
好的 多谢
