### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by jiachengliu** [QMUI/QMUI_Android#249]
### 运行环境 ###

- [x] 设备型号：如：`小米 note3`
- [x] 设备系统版本：如 `Android 7.1.1`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.1.2`、0.0.4

### 具体问题描述 ###
异常闪退
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/12412647/39223738-48c45acc-4876-11e8-956d-caf3575eb680.png)
#### 异常日志（堆栈） ####
`E/CrashHandler: In thread: Thread[main,5,main]
                                                                   UncaughtException detected: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@d8de227
                                                                       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1271)
                                                                       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:257)
                                                                       at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
                                                                       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:528)
                                                                       at android.widget.TextView.onDraw(TextView.java:5774)
                                                                       at android.view.View.draw(View.java:17211)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16193)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.draw(View.java:17214)
                                                                       at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1643)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16193)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.draw(View.java:17214)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16193)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at com.qmuiteam.qmui.arch.SwipeBackLayout.drawChild(SwipeBackLayout.java:394)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16188)
                                                                       at android.view.View.draw(View.java:16977)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
                                                                       at android.view.View.draw(View.java:17214)
                                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:756)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16193)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2866)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2665)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2272)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1311)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6431)
                                                                   	at android.view.Choreograp`

**Comment by cgspine** [comment]
这是 bitmap 回收出错了吧， 类似 http://zwnjava.iteye.com/blog/1901880
