### ISSUE TITLE
Demo跑不起来

### ISSUE THREAD

**Issue by tinggu** [QMUI/QMUI_Android#26]
### 运行环境 ###

- [x] 设备型号：如：`小米note `
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.0`

#### 异常日志（堆栈） ####
 Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:359)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:280)
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:145)
                                                                           at com.qmuiteam.qmuidemo.base.BaseFragmentActivity.onCreate(BaseFragmentActivity.java:24)
                                                                           at com.qmuiteam.qmuidemo.QDMainActivity.onCreate(QDMainActivity.java:19)
                                                                           at android.app.Activity.performCreate(Activity.java:6112)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:160) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5372)

**Comment by cgspine** [comment]
git clone 下来就无法运行吗？还是你有更改过？这个错误看起来像是 theme 没有继承自 QMUI.Compat.NoActionBar。

**Comment by majiag** [comment]
supportVersion 是多少？buildToolsVersion?

**Comment by Icando26** [comment]
我的也跑不上来  没有这个QDWidgetContainer类

**Comment by cgspine** [comment]
QDWidgetContainer是编译器生成的，clear一下再重新编译看看？
