### ISSUE TITLE
QMUITabSegment只添加一个Fragment出现IndexOutOfBoundsException异常

### ISSUE THREAD

**Issue by tpnet** [QMUI/QMUI_Android#270]
### 运行环境 ###

- [x] 设备型号：如：`小米note`
- [x] 设备系统版本：如 `Android 8.1`
- [x] Gradle 版本：如 `3.1.2`
- [x] QMUI Android 版本：`1.1.0`

### 具体问题描述 ###

只add一个Fragment

```
        val titleList = arrayListOf("综合")
        mFragmentList.add(ContestListFragment.newInstance(ContestListActivity.TYPE_ALL))
        mAdapter = PagerNormalAdapter(supportFragmentManager, mFragmentList, titleList)
        viewPager.adapter = mAdapter

        tabSegment.setHasIndicator(true)
        tabSegment.setIndicatorPosition(false)
        tabSegment.setIndicatorWidthAdjustContent(true)
        /*mTabSegment.addTab(QMUITabSegment.Tab(mTitleList?.get(0)))
        mTabSegment.addTab(QMUITabSegment.Tab(mTitleList?.get(1)))
        mTabSegment.addTab(QMUITabSegment.Tab(mTitleList?.get(2)))*/
        tabSegment.setupWithViewPager(viewPager, true)
        tabSegment.mode = QMUITabSegment.MODE_FIXED
```

#### 问题截图 ####
UncaughtException detected: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.qmuiteam.qmui.widget.QMUIItemViewsAdapter.getItem(QMUIItemViewsAdapter.java:108)
        at com.qmuiteam.qmui.widget.QMUITabSegment.updateIndicatorPosition(QMUITabSegment.java:721)
        at com.qmuiteam.qmui.widget.QMUITabSegment$TabLayoutOnPageChangeListener.onPageScrolled(QMUITabSegment.java:987)
        at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1924)
        at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1898)
        at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1836)
        at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:688)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1780)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/39987380-33afaa9e-5797-11e8-9aae-35f0ae50d35c.png)
这里不可能出现数组越界啊。除非有线程错误？

**Comment by tpnet** [comment]
@cgspine  position == mItemData.size() ,,,   也是数组越界，，，，  你没判断等于

**Comment by cgspine** [comment]
好，眼瞎。我检查下

**Comment by cgspine** [comment]
我在 QD 里面尝试好像是正确的。另外比较奇怪的是为何只有一个 item 可以触发onPageScroll ？ 能否提供下 PagerNormalAdapter 的代码？

**Comment by tpnet** [comment]
@cgspine  

···
class PagerNormalAdapter(manager: FragmentManager, var fragmnetList: List<Fragment>, var titleList: List<String>) 
    : FragmentPagerAdapter(manager) {
    
    override fun getItem(position: Int): Fragment = fragmnetList[position]
    override fun getCount(): Int = fragmnetList.size

    override fun getPageTitle(position: Int): CharSequence = if (position >= titleList.size) {
        ""
    } else {
        titleList[position]
    }

    override fun destroyItem(container: ViewGroup, position: Int, obj: Any) {
//        super.destroyItem(container, position, `object`)
    }
    
    
    
}
···

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/39990642-abce69ea-579f-11e8-9baa-ce1022061a79.png)
能再这里断点下吗？我这边还是无法复现，我想看看此时 positionOffset 是多少

**Comment by tpnet** [comment]
@cgspine   不好意思，你没艾特我，我不知道你已经回复我了，，我今天又试了一下，，，改为一个Fragment， 又不会崩溃了，，，，好奇怪，，，

**Comment by tpnet** [comment]
刚刚调试 不会崩溃时候，为0。。我也复现不了了，，难道是我当时大意有什么搞错了吗

![image](https://user-images.githubusercontent.com/17380722/40213186-bb562814-5a86-11e8-9205-736dec046a84.png)

**Comment by cgspine** [comment]
可能是数据有问题吧，1.1.3版本目前我添加了保护，但是对发现问题也不会有太大帮助
