### ISSUE TITLE
java.io.FileNotFoundException: /system/build.prop (Permission denied)

### ISSUE THREAD

**Issue by qslx2015** [QMUI/QMUI_Android#272]
### 运行环境 ###

- [x] 设备型号：如：`华为 mate 10 pro`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `4.4`
- [x] QMUI Android 版本：最新

### 具体问题描述 ###
没有权限读/system/build.pro 

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/12878424/39993548-ce2ca94e-57a8-11e8-99c1-3bb70936319c.png)

#### 异常日志（堆栈） ####
java.io.FileNotFoundException: /system/build.prop (Permission denied)
                                                                              at java.io.FileInputStream.open0(Native Method)
                                                                              at java.io.FileInputStream.open(FileInputStream.java:200)
                                                                              at java.io.FileInputStream.<init>(FileInputStream.java:150)
                                                                              at com.seewo.easicare.utils.qmui.QMUIDeviceHelper.<clinit>(QMUIDeviceHelper.java:43)
                                                                              at com.seewo.easicare.utils.qmui.QMUIDeviceHelper.isMeizu(QMUIDeviceHelper.java:162)
                                                                              at com.seewo.easicare.utils.qmui.QMUIStatusBarHelper.initStatusBarHeight(QMUIStatusBarHelper.java:350)
                                                                              at com.seewo.easicare.utils.qmui.QMUIStatusBarHelper.getStatusbarHeight(QMUIStatusBarHelper.java:338)
                                                                              at com.seewo.easicare.ui.fragments.TeacherClassroomFragment.initStatusBar(TeacherClassroomFragment.java:109)
                                                                              at com.seewo.easicare.ui.fragments.TeacherClassroomFragment.onViewCreated(TeacherClassroomFragment.java:100)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                              at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                              at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                              at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                              at com.seewo.easicare.base.CareTitleBaseActivity.onStart(CareTitleBaseActivity.java:135)
                                                                              at com.seewo.easicare.ui.CareMainActivity.onStart(CareMainActivity.java:308)
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1339)
                                                                              at android.app.Activity.performStart(Activity.java:7392)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3157)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
                                                                              at android.app.ActivityThread.-wrap12(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                              at android.os.Looper.loop(Looper.java:166)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by qslx2015** [comment]
那8.0以后有对应的系统判断方法？

**Comment by cgspine** [comment]
原本读取 /system/build.prop 是一种比较快的方式一次拿到所有值， 否则就只能通过android.os.SystemProperties 去反射取值。8.0 就只能用后面的方式了
