### ISSUE TITLE
用的是5.1系统设置透明状态栏异常，但不影响运行

### ISSUE THREAD

**Issue by javakam** [QMUI/QMUI_Android#318]
### 运行环境 ###

- [x] 设备型号：如：`KT45Q`
- [x] 设备系统版本：如 `Android 5.1`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
5.1系统设置透明状态栏抛出的异常，但不影响运行

#### 问题截图 ####
[https://raw.githubusercontent.com/javakam/image/master/issue-20180617144940.png](https://raw.githubusercontent.com/javakam/image/master/issue-20180617144940.png)
#### 异常日志（堆栈） ####
异常日志，
`
6-17 14:47:36.725 25177-25177/com.ishiqing D/AccessibilityManager: setStateLocked: wasEnabled = false, mIsEnabled = false, wasTouchExplorationEnabled = false, mIsTouchExplorationEnabled = false, wasHighTextContrastEnabled = false, mIsHighTextContrastEnabled = false
    java.lang.Throwable: setStateLocked
        at android.view.accessibility.AccessibilityManager.setStateLocked(AccessibilityManager.java:553)
        at android.view.accessibility.AccessibilityManager.tryConnectToServiceLocked(AccessibilityManager.java:636)
        at android.view.accessibility.AccessibilityManager.<init>(AccessibilityManager.java:226)
        at android.view.accessibility.AccessibilityManager.getInstance(AccessibilityManager.java:206)
        at android.view.View.setFlags(View.java:9843)
        at android.view.ViewGroup.initViewGroup(ViewGroup.java:536)
        at android.view.ViewGroup.<init>(ViewGroup.java:525)
        at android.view.ViewGroup.<init>(ViewGroup.java:520)
        at android.view.ViewGroup.<init>(ViewGroup.java:516)
        at android.view.ViewGroup.<init>(ViewGroup.java:512)
        at android.widget.FrameLayout.<init>(FrameLayout.java:119)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.<init>(PhoneWindow.java:2326)
        at com.android.internal.policy.impl.PhoneWindow.generateDecor(PhoneWindow.java:3463)
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3849)
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:2042)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:69)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:38)
        at com.ishiqing.base.qmui.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:31)
        at com.ishiqing.MainActivity.onCreate(MainActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
`
问题出现在：
[QMUIStatusBarHelper](https://github.com/QMUI/QMUI_Android/blob/3107098abffe1de5bf616ed12fea91f19bdfe610/qmui/src/main/java/com/qmuiteam/qmui/util/QMUIStatusBarHelper.java) 中的
`
  window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
`

**Comment by cgspine** [comment]
你在什么时机调用的 translucent() 方法？

**Comment by javakam** [comment]
`protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        QMUIStatusBarHelper.translucent(this);
        mFragmentContainer = new QMUIWindowInsetLayout(this);
        mFragmentContainer.setId(getContextViewId());
        setContentView(mFragmentContainer);
    }`

**Comment by javakam** [comment]
Here ：   QMUI_Android/arch/src/main/java/com/qmuiteam/qmui/arch/QMUIFragmentActivity.java

**Comment by javakam** [comment]
这里：  [QMUI_Android/arch/src/main/java/com/qmuiteam/qmui/arch/QMUIFragmentActivity.java](QMUI_Android/arch/src/main/java/com/qmuiteam/qmui/arch/QMUIFragmentActivity.java)
