### ISSUE TITLE
QMUIPullRefreshLayout无法正常显示

### ISSUE THREAD

**Issue by XinwenCheng** [QMUI/QMUI_Android#337]
### 运行环境 ###
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
添加QMUIPullRefreshLayout到布局文件，运行项目，界面黑屏，异常信息附在后面。调了好久，来回对比官方demo项目，没发现什么区别，请解答，谢谢！

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/app_primary_color">

    <com.qmuiteam.qmui.widget.QMUITopBar
        android:id="@+id/topbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/qmui_topbar_height" />

    <com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout
        android:id="@+id/pull_to_refresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="?attr/qmui_topbar_height"
        android:background="?attr/qmui_config_color_background">

        <ListView
            android:id="@+id/listview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/qmui_config_color_white"
            android:divider="@drawable/qmui_divider"
            android:dividerHeight="1px" />
    </com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout>
</FrameLayout>
```
#### 异常日志（堆栈） ####
```bash
07-07 08:29:55.048 10333-10333/com.easyto.aihw.meetingassistantelite E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.easyto.aihw.meetingassistantelite, PID: 10333
    android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout
    Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.easyto.aihw.meetingassistantelite.ui.record.RecordListFragment.onCreateView(RecordListFragment.java:37)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
        at android.view.View.measure(View.java:23279)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23279)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:23279)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23279)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23279)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23279)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:898)
07-07 08:29:55.050 10333-10333/com.easyto.aihw.meetingassistantelite E/AndroidRuntime:     at android.view.View.measure(View.java:23279)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2873)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1910)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2165)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7800)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/widget/CircularProgressDrawable;
        at com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout$RefreshView.<init>(QMUIPullRefreshLayout.java:963)
        at com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout.createRefreshView(QMUIPullRefreshLayout.java:210)
        at com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout.addRefreshView(QMUIPullRefreshLayout.java:215)
        at com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout.<init>(QMUIPullRefreshLayout.java:140)
        at com.qmuiteam.qmui.widget.pullRefreshLayout.QMUIPullRefreshLayout.<init>(QMUIPullRefreshLayout.java:124)
        	... 66 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.widget.CircularProgressDrawable" on path: DexPathList[[zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/base.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_dependencies_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_resources_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_0_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_1_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_2_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_3_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_4_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_5_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_6_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_7_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_8_apk.apk", zip file "/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 71 more
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.easyto.aihw.meetingassistantelite-Z2hs7r6Ht42zTxakuIWT-g==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
07-07 08:29:55.051 10333-10333/com.easyto.aihw.meetingassistantelite E/AndroidRuntime:     at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5937)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        		... 5 more
```

**Comment by cgspine** [comment]
Didn't find class "android.support.v4.widget.CircularProgressDrawable"

qmui 高版本依赖 CircularProgressDrawable， 这里是 support 包的版本不够高，建议升级下 support 包。

**Comment by XinwenCheng** [comment]
好的，已解决，谢谢！
