### ISSUE TITLE
创建 QMUITipDialog 崩溃

### ISSUE THREAD

**Issue by XingHangTester** [QMUI/QMUI_Android#338]
### 运行环境 ###

- [x] 设备型号：如：`华为P 20`
- [x] 设备系统版本：如 `Android 8.1`
- [x] Gradle 版本：如 `4.4.0`
- [x] QMUI Android 版本：`1.1.3` 1.1.5 也崩溃

### 具体问题描述 ###
已经修改 AppTheme  parent="QMUI.Compat" ，

tipDialog = new QMUITipDialog.Builder(getApplicationContext())
                .setIconType(QMUITipDialog.Builder.ICON_TYPE_LOADING)
                .setTipWord("正在加载")
                .create();
        tipDialog.show();

#### 异常日志（堆栈） [####[]

   Process: com.yxinsur.insuranceman, PID: 10431
    android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
        at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:478)
        at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:321)
        at android.app.Dialog.setContentView(Dialog.java:647)
        at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:141)
        at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:129)
        at com.yxinsur.insuranceman.base.BaseActivity.loading(BaseActivity.java:42)
        at com.yxinsur.insuranceman.ui.activity.LoginActivity.onViewClicked(LoginActivity.java:60)
        at com.yxinsur.insuranceman.ui.activity.LoginActivity_ViewBinding$2.doClick(LoginActivity_ViewBinding.java:54)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:6329)
        at android.view.View$PerformClick.run(View.java:25004)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7367)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f030209 a=7}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:996)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
        at android.view.View.<init>(View.java:4784)
        at android.view.ViewGroup.<init>(ViewGroup.java:597)
        at android.widget.LinearLayout.<init>(LinearLayout.java:237)
        at android.widget.LinearLayout.<init>(LinearLayout.java:233)
        at android.widget.LinearLayout.<init>(LinearLayout.java:229)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:658) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64) 
        at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:478) 
        at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:321) 
        at android.app.Dialog.setContentView(Dialog.java:647) 
        at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:141) 
        at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:129) 
        at com.yxinsur.insuranceman.base.BaseActivity.loading(BaseActivity.java:42) 
        at com.yxinsur.insuranceman.ui.activity.LoginActivity.onViewClicked(LoginActivity.java:60) 
        at com.yxinsur.insuranceman.ui.activity.LoginActivity_ViewBinding$2.doClick(LoginActivity_ViewBinding.java:54) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
        at android.view.View.performClick(View.java:6329) 
        at android.view.View$PerformClick.run(View.java:25004) 
        at android.os.Handler.handleCallback(Handler.java:809) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7367)

**Comment by cgspine** [comment]
dialog 是不能用 application 的 context 的
