### ISSUE TITLE
android.view.InflateException: Binary XML file line #7: Binary XML file line #7: You must supply a layout_width attribute.                   Caused by: java.lang.UnsupportedOperationException: Binary XML file line #7: You must supply a layout_width attribute.

### ISSUE THREAD

**Issue by skybebe** [QMUI/QMUI_Android#364]
### 运行环境 ###

- [x] 设备型号：Huawei Honor A7
- [x] 设备系统版本：8.0
- [x] Gradle 版本：3.2
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
调用QMUIBottomSheet时报错如上。
调用代码如下
@Override
    protected View onCreateView() {
        Logger.i("BottomSheetFragment onCreateView");
        View view = LayoutInflater.from(getActivity()).inflate(R.layout.demo2, null);
        ButterKnife.bind(this, view);
        return view;
    }
    @OnClick(R.id.share_to_btn2)
    public void onClickBtn(View view) {
        Logger.i("onClickBtn");

        showBottomSheetGrid();
    }
   private void showBottomSheetGrid() {
        Logger.i("BottomSheetFragment showBottomSheetGrid");
        final int TAG_SHARE_WECHAT_FRIEND = 0;
        final int TAG_SHARE_WECHAT_MOMENT = 1;
        final int TAG_SHARE_WEIBO = 2;
        final int TAG_SHARE_CHAT = 3;
        final int TAG_SHARE_LOCAL = 4;
        Activity activity = getActivity();
        if (activity == null) {
            Logger.e("activity null in BottomSheetFragment");
            return;
        }
        QMUIBottomSheet.BottomGridSheetBuilder builder = new QMUIBottomSheet.BottomGridSheetBuilder(activity);
        builder.addItem(R.mipmap.icon_more_operation_share_friend, activity.getString(R.string.share_to_wx), TAG_SHARE_WECHAT_FRIEND, QMUIBottomSheet.BottomGridSheetBuilder.FIRST_LINE)
                .addItem(R.mipmap.icon_more_operation_share_moment, activity.getString(R.string.share_to_wx_timeline), TAG_SHARE_WECHAT_MOMENT, QMUIBottomSheet.BottomGridSheetBuilder.FIRST_LINE)
                .addItem(R.mipmap.icon_more_operation_save, activity.getString(R.string.share_to_local_save), TAG_SHARE_LOCAL, QMUIBottomSheet.BottomGridSheetBuilder.SECOND_LINE)
                .setOnSheetItemClickListener(new QMUIBottomSheet.BottomGridSheetBuilder.OnSheetItemClickListener() {
                    @Override
                    public void onClick(QMUIBottomSheet dialog, View itemView) {
                        dialog.dismiss();
                        int tag = (int) itemView.getTag();
                        switch (tag) {
                            case TAG_SHARE_WECHAT_FRIEND:
                                Toast.makeText(getActivity(), "分享到微信", Toast.LENGTH_SHORT).show();
                                break;
                            case TAG_SHARE_WECHAT_MOMENT:
                                Toast.makeText(getActivity(), "分享到朋友圈", Toast.LENGTH_SHORT).show();
                                break;
                           
                            case TAG_SHARE_LOCAL:
                                Toast.makeText(getActivity(), "保存到本地", Toast.LENGTH_SHORT).show();
                                break;
                        }
                    }
                }).build().show();
    }
#### 异常日志（堆栈） ####
android.view.InflateException: Binary XML file line #7: Binary XML file line #7: You must supply a layout_width attribute.
                  Caused by: java.lang.UnsupportedOperationException: Binary XML file line #7: You must supply a layout_width attribute.
                      at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:820)
                      at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7632)
                      at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7824)
                      at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2001)
                      at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1899)
                      at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1897)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:876)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet$BottomGridSheetBuilder.createItemView(QMUIBottomSheet.java:639)
                      at com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet$BottomGridSheetBuilder.addItem(QMUIBottomSheet.java:621)
                      at com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet$BottomGridSheetBuilder.addItem(QMUIBottomSheet.java:592)
                      at com.daxiangbanka.fragment.BottomSheetFragment.showBottomSheetGrid(BottomSheetFragment.java:118)
                      at com.daxiangbanka.fragment.BottomSheetFragment.onClickBtn(BottomSheetFragment.java:74)
                      at com.daxiangbanka.fragment.BottomSheetFragment_ViewBinding$1.doClick(BottomSheetFragment_ViewBinding.java:31)
                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                      at android.view.View.performClick(View.java:6291)
                      at android.view.View$PerformClick.run(View.java:24931)
                      at android.os.Handler.handleCallback(Handler.java:808)
                      at android.os.Handler.dispatchMessage(Handler.java:101)
                      at android.os.Looper.loop(Looper.java:166)
                      at android.app.ActivityThread.main(ActivityThread.java:7425)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by skybebe** [comment]
layout_width 要怎么加？给谁加呢？

**Comment by skybebe** [comment]
补充：我在minifest中给application指定了android:theme="@style/AppTheme"，AppTheme是继承QMUI.Compat

**Comment by skybebe** [comment]
救命啊

**Comment by cgspine** [comment]
1. getLayoutDimension 出错，检查下 dimen.xml 是否有遗漏单位？ 如果少了 “dp”, 也有可能触发这种错误
2. QMUIDemo 在你的手机上是否正常？
3. 能否提供下页面发白的 layout inspector 文件？

**Comment by Demonhuang** [comment]
这个问题解决了 我也遇到了这个问题
