### ISSUE TITLE
低版本问题

### ISSUE THREAD

**Issue by Bruce-Romance** [QMUI/QMUI_Android#376]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 4.0.4`
- [x] Gradle 版本：如 `4.4.0`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
在低版本API15会崩溃，提示找不到方法
#### 异常日志（堆栈） ####
java.lang.NoSuchMethodError: com.qmuiteam.qmui.layout.QMUIButton.setBackground
                                                                     at com.qmuiteam.qmui.widget.dialog.QMUIDialogAction.generateActionButton(QMUIDialogAction.java:123)
                                                                     at com.qmuiteam.qmui.widget.dialog.QMUIDialogAction.buildActionView(QMUIDialogAction.java:105)
                                                                     at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.onCreateHandlerBar(QMUIDialogBuilder.java:402)
                                                                     at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:301)
                                                                     at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:274)
                                                                     at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.show(QMUIDialogBuilder.java:263)

**Comment by Bruce-Romance** [comment]
楼上似乎没理解我Is的意思，这个崩溃是没做容错，应该是个Bug来的。你看了QMUI的文档介绍就知道它是支持API14及以上的
