### ISSUE TITLE
QMUIGroupListView异常

### ISSUE THREAD

**Issue by littlejigege** [QMUI/QMUI_Android#38]
### 运行环境 ###

- [x] 设备型号：如：`MI 5`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `4.1`
- [x] QMUI Android 版本：`1.0.2`

### 具体问题描述 ###
在使用QMUIGroupListView的时候出现异常
没添加item时正常，一旦newsetion就报错

#### 问题截图 ####
![使用代码](https://user-images.githubusercontent.com/26401025/30278275-8f777454-973c-11e7-8c3f-0b9eebf82b3d.png)
![布局](https://user-images.githubusercontent.com/26401025/30278277-90174ae2-973c-11e7-922d-bc9a816d5ecd.png)

#### 异常日志（堆栈） ####
FATAL EXCEPTION: main
                                                                   Process: com.qg.musicmaven, PID: 15863
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qg.musicmaven/com.qg.musicmaven.ui.SettingsActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:163)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6315)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
                                                                    Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:742)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:810)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
                                                                       at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.init(QMUIGroupListSectionHeaderFooterView.java:58)
                                                                       at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.<init>(QMUIGroupListSectionHeaderFooterView.java:37)
                                                                       at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.<init>(QMUIGroupListSectionHeaderFooterView.java:27)
                                                                       at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.<init>(QMUIGroupListSectionHeaderFooterView.java:41)
                                                                       at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListView$Section.createSectionHeader(QMUIGroupListView.java:383)
                                                                       at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListView$Section.setTitle(QMUIGroupListView.java:268)
                                                                       at com.qg.musicmaven.ui.SettingsActivity.initGroupListView(SettingsActivity.kt:46)
                                                                       at com.qg.musicmaven.ui.SettingsActivity.initView(SettingsActivity.kt:40)
                                                                       at com.qg.musicmaven.ui.SettingsActivity.onCreate(SettingsActivity.kt:34)
                                                                       at android.app.Activity.performCreate(Activity.java:6847)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:163)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6315)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040156 a=-1}
                                                                       at android.content.res.TypedArray.getColorStateList(TypedArray.java:530)
                                                                       at android.widget.TextView.<init>(TextView.java:1076)
                                                                       at android.widget.TextView.<init>(TextView.java:704)

**Comment by cgspine** [comment]
>Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040156 a=-1}

我猜想你的这个activity没有引用 QMUI.Compat 主题

**Comment by littlejigege** [comment]
对的，我太粗心了，这个活动重新指定了theme，导致app的theme无效，谢谢
