### ISSUE TITLE
适配AndroidX

### ISSUE THREAD

**Issue by xtsxx** [QMUI/QMUI_Android#417]
### 具体问题描述 ###
有不少开源库已经转换到AndroidX版本的support库，是否有更新到AndroidX的计划？

**Comment by cgspine** [comment]
短时间内应该不会。因为目前并不影响使用，在 `gradle.properies` 里添加 `android.enableJetifier=true` 就可以了。

**Comment by chinaluopiao** [comment]
2019年是否有更新到AndroidX的计划？

**Comment by kingctan** [comment]
启用androidx后，改：
···
<style name="AppTheme" parent="QMUI.Compat.NoActionBar">
···
运行后，就挂了。
报错：
···
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zwzbrowser, PID: 18860
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zwzbrowser/com.zwzbrowser.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3082)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
        at androidx.navigation.ui.ActionBarOnDestinationChangedListener.setTitle(ActionBarOnDestinationChangedListener.java:48)
        at androidx.navigation.ui.AbstractAppBarOnDestinationChangedListener.onDestinationChanged(AbstractAppBarOnDestinationChangedListener.java:100)
        at androidx.navigation.NavController.addOnDestinationChangedListener(NavController.java:218)
        at androidx.navigation.ui.NavigationUI.setupActionBarWithNavController(NavigationUI.java:220)
        at com.zwzbrowser.MainActivity.onCreate(MainActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
···

**Comment by kingctan** [comment]
@cgspine 有什么办法没？几个设置都加上了。

**Comment by kingctan** [comment]
AndroidX must be enabled when Jetifier is enabled. To resolve, set android.useAndroidX=true in your gradle.properties file.

报错。@cgspine

**Comment by cgspine** [comment]
在 gradle.properies 里添加 android.useAndroidX=true, android.enableJetifier=true ?
