### ISSUE TITLE
Fragment滑动Crash

### ISSUE THREAD

**Issue by zxxcos** [QMUI/QMUI_Android#421]
### 运行环境 ###

- [x] 设备型号：如：`OPPOR9m`
- [x] 设备系统版本：如 `Android 5.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###
Lab—>QMUIFragment功能手动多滑几次，速度稍稍快一点，crash！
#### 异常日志（堆栈） ####
 Process: com.qmuiteam.qmuidemo, PID: 8171
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4093)
        at android.view.ViewGroup.addView(ViewGroup.java:3943)
        at android.view.ViewGroup.addView(ViewGroup.java:3884)
        at com.qmuiteam.qmui.arch.QMUIFragment$2.onEdgeTouch(QMUIFragment.java:374)
        at com.qmuiteam.qmui.arch.SwipeBackLayout$ViewDragCallback.tryCaptureView(SwipeBackLayout.java:472)
        at android.support.v4.widget.ViewDragHelper.tryCaptureViewForDrag(ViewDragHelper.java:908)
        at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:984)
        at com.qmuiteam.qmui.arch.SwipeBackLayout.onInterceptTouchEvent(SwipeBackLayout.java:362)

**Comment by huaxi** [comment]
设备型号：红米5A
  设备系统版本：Android 7.1.2
  Gradle 版本：4.6
  QMUI Android 版本：1.1.7

我的也是一样的情况

**Comment by cgspine** [comment]
现在可以升级到 0.2.0 了。 fix 了这个问题， 并且支持 activity 手势返回了。 不过现在需要在 `Application.onCreate()` 里调用 `QMUISwipeBackActivityManager.init(this)`
