### ISSUE TITLE
release混淆后没办法使用debug下混淆可以正常使用

### ISSUE THREAD

**Issue by Cghang** [QMUI/QMUI_Android#422]
### 运行环境 ###

- [x] 设备型号：如：`VIVO X9`
- [x] 设备系统版本：如 `Android 6.0.1`
- [x] Gradle 版本：如 `3.1.4`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.dany.mzhipay/com.dany.mzhipay.LoginActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.qmuiteam.qmui.widget.QMUITopBar

在混淆后就会这样 但是debug下混淆不会出错 
打包出来安装就会出错 实在找不到原因 求助官方
谢谢
#### 问题截图 ####
闪退

#### 异常日志（堆栈） ####

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.dany.mzhipay/com.dany.mzhipay.LoginActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.qmuiteam.qmui.widget.QMUITopBar
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
3 ......
4 Caused by:
5 java.lang.NoSuchMethodError:No virtual method obtainStyledAttributes(Landroid/util/AttributeSet;[III)Landroid/content/res/b; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
6 com.qmuiteam.qmui.widget.QMUITopBar.init(QMUITopBar.java:119)
7 com.qmuiteam.qmui.widget.QMUITopBar.<init>(QMUITopBar.java:81)
8 com.qmuiteam.qmui.widget.QMUITopBar.<init>(QMUITopBar.java:85)
9 java.lang.reflect.Constructor.newInstance(Native Method)
10 android.view.LayoutInflater.createView(LayoutInflater.java:619)
11 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
12 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
13 android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
14 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
15 android.view.LayoutInflater.inflate(LayoutInflater.java:515)
16 de.robv.android.xp0sed.Xp0sedBridge.invokeOriginalMethodNative(Native Method)
17 de.robv.android.xp0sed.Xp0sedBridge.handleHookedMethod(Xp0sedBridge.java:334)
18 android.view.LayoutInflater.inflate(<Xp0sed>)
19 android.view.LayoutInflater.inflate(LayoutInflater.java:423)
20 android.view.LayoutInflater.inflate(LayoutInflater.java:374)
21 com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
22 android.app.Activity.setContentView(Activity.java:2183)
23 com.dany.mzhipay.LoginActivity.onCreate(LoginActivity.java:34)
24 android.app.Activity.performCreate(Activity.java:6262)
25 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
26 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
27 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
28 android.app.ActivityThread.-wrap11(ActivityThread.java)
29 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
30 android.os.Handler.dispatchMessage(Handler.java:102)
31 android.os.Looper.loop(Looper.java:148)
32 android.app.ActivityThread.main(ActivityThread.java:5415)
33 java.lang.reflect.Method.invoke(Native Method)
34 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
35 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by Cghang** [comment]
> 必现？在 Android Studio 中试试 `File | Invalidate Caches/Restart` ?

不行 很奇怪 我这边反编译的话 是可以看到那个包名的

**Comment by Cghang** [comment]
aused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:631)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
        at android.app.Activity.setContentView(Activity.java:2387) 
        at com.dany.mzhipay.LoginActivity.onCreate(LoginActivity.java:34) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244) 
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:99) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7232) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: java.lang.NoSuchMethodError: No virtual method getTheme()Landroid/content/res/Resources$a; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
        at com.qmuiteam.qmui.a.f.a(QMUIResHelper.java:25)
        at com.qmuiteam.qmui.layout.a.<init>(QMUILayoutHelper.java:98)
        at com.qmuiteam.qmui.layout.QMUILinearLayout.a(QMUILinearLayout.java:34)
        at com.qmuiteam.qmui.layout.QMUILinearLayout.<init>(QMUILinearLayout.java:25)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
        at android.app.Activity.setContentView(Activity.java:2387) 
        at com.dany.mzhipay.LoginActivity.onCreate(LoginActivity.java:34) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244) 
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:99) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7232) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

求大神们看看

**Comment by Cghang** [comment]
一混淆就出错 不混淆就没问题 //脑阔疼

**Comment by cgspine** [comment]
https://github.com/Kotlin/anko/issues/311

用了 anko ? 找到个类似的堆栈

**Comment by Cghang** [comment]
> [Kotlin/anko#311](https://github.com/Kotlin/anko/issues/311)
> 
> 用了 anko ? 找到个类似的堆栈

不是 算了。。不搞混淆了 以后再看看吧 谢了
