### ISSUE TITLE
点击QMUIDialog.CustomDialogBuilder弹出框自定义上面的按钮跳转到相机拍摄照片后把相片显示在CustomDialogBuilder上 ，多操作两遍就会崩溃

### ISSUE THREAD

**Issue by as11051105** [QMUI/QMUI_Android#447]
### 运行环境 ###

- [x] 设备型号：如：`乐视`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `4.1.0`
- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###
点击QMUIDialog.CustomDialogBuilder弹出框自定义上面的按钮跳转到相机拍摄照片后把相片显示在CustomDialogBuilder上 ，多操作两遍就会崩溃

#### 异常日志（堆栈） ####
` java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c27eefa
        at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
        at android.widget.ImageView.onDraw(ImageView.java:1246)
        at android.view.View.draw(View.java:16535)
        at android.view.View.updateDisplayListIfDirty(View.java:15525)
        at android.view.View.draw(View.java:16305)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3718)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3508)
        at android.view.View.updateDisplayListIfDirty(View.java:15520)
        at android.view.View.draw(View.java:16305)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3718)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3508)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2070)
        at android.view.View.draw(View.java:16538)
        at android.view.View.updateDisplayListIfDirty(View.java:15525)
        at android.view.View.draw(View.java:16305)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3718)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3508)
        at com.qmuiteam.qmui.layout.QMUILinearLayout.dispatchDraw(QMUILinearLayout.java:217)
        at com.qmuiteam.qmui.widget.dialog.QMUIDialogView.dispatchDraw(QMUIDialogView.java:68)
        at android.view.View.draw(View.java:16538)
        at android.view.View.updateDisplayListIfDirty(View.java:15525)
        at android.view.View.draw(View.java:16305)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3718)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3508)
        at android.view.View.updateDisplayListIfDirty(View.java:15520)
        at android.view.View.draw(View.java:16305)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3718)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3508)
        at android.view.View.updateDisplayListIfDirty(View.java:15520)
        at android.view.View.draw(View.java:16305)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3718)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3508)
        at android.view.View.updateDisplayListIfDirty(View.java:15520)
        at android.view.View.draw(View.java:16305)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3718)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3508)
        at android.view.View.draw(View.java:16538)
        at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2756)
        at android.view.View.updateDisplayListIfDirty(View.java:15525)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2973)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2785)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2403)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1274)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6644)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
        at android.view.Choreographer.doCallbacks(Choreographer.java:717)
        at android.view.Choreographer.doFrame(Choreographer.java:652)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by cgspine** [comment]
这是你的 Bitmap 被 recycle 了吧，检查下 recycle 的调用？
