### ISSUE TITLE
侧滑关闭闪屏

### ISSUE THREAD

**Issue by andrew203** [QMUI/QMUI_Android#449]
### 运行环境 ###

- [x] 设备型号：如：`三星S6 SM-G9250`
- [x] 设备系统版本：如 `Android 6.0.1`
- [x] Gradle 版本：如 `4.6`
- [x] QMUI Android 版本：`1.1.10`

### 具体问题描述 ###
从Fragment跳到Activity，再从Activity侧滑关闭回到  fragment时  屏幕闪烁。

#### 异常日志（堆栈） ####
11-30 15:29:45.922 9814-9814/com.ao.supermanager D/ViewRootImpl: ViewPostImeInputStage processPointer 0
11-30 15:29:46.152 9814-9814/com.ao.supermanager D/ViewRootImpl: ViewPostImeInputStage processPointer 1
11-30 15:29:46.662 9814-9814/com.ao.supermanager D/ViewRootImpl: ViewPostImeInputStage processPointer 0
11-30 15:29:46.672 9814-9814/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch: edgeFlag = 1
11-30 15:29:46.672 9814-9814/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 1 ;scrollPercent = 0.0
11-30 15:29:46.782 9814-9814/com.ao.supermanager D/ViewRootImpl: ViewPostImeInputStage processPointer 1
11-30 15:29:46.782 9814-9814/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 2 ;scrollPercent = 0.18575063
11-30 15:29:47.232 9814-9814/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 0 ;scrollPercent = 1.0063614
11-30 15:29:47.232 9814-9814/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.InputWifiActivity onPaused <<<
11-30 15:29:47.242 9814-9814/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
11-30 15:29:47.252 9814-9814/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onResumed <<<
11-30 15:29:47.252 9814-9814/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
11-30 15:29:47.262 9814-9875/com.ao.supermanager D/mali_winsys: new_window_surface returns 0x3000,  [1440x2560]-format:1
11-30 15:29:47.262 9814-9814/com.ao.supermanager W/ActivityThread: AppLock checkAppLockState isAppLocked = false pkgName = com.ao.supermanager showWhenLocked = false
11-30 15:29:47.292 9814-9814/com.ao.supermanager I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@a62807c time:22509180
11-30 15:29:47.312 9814-9814/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.InputWifiActivity onDestroyed <<<
11-30 15:29:47.312 9814-9814/com.ao.supermanager D/ViewRootImpl: #3 mView = null

**Comment by huaxi** [comment]
好像并不只是Fragment和Activity跳转， 只要当前的有网络请求然后请求回来，刷新界面，（recylcerView）处于刷时这时候又刚好 手指侧滑到一半， 会发现 前一个的Fragment闪动了一下

**Comment by andrew203** [comment]
升级到0.2.3   依旧闪屏

**Comment by andrew203** [comment]
2018-12-27 08:45:27.629 4675-4718/com.ao.supermanager I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2018-12-27 08:45:27.633 4675-4718/com.ao.supermanager I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2018-12-27 08:45:27.633 4675-4718/com.ao.supermanager I/OpenGLRenderer: Initialized EGL, version 1.4
2018-12-27 08:45:27.633 4675-4718/com.ao.supermanager D/OpenGLRenderer: Swap behavior 1
2018-12-27 08:45:27.633 4675-4718/com.ao.supermanager W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2018-12-27 08:45:27.633 4675-4718/com.ao.supermanager D/OpenGLRenderer: Swap behavior 0
2018-12-27 08:45:27.644 4675-4718/com.ao.supermanager D/EGL_emulation: eglCreateContext: 0xe8e6de60: maj 3 min 0 rcv 3
2018-12-27 08:45:27.647 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:45:27.714 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:45:44.254 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LoginActivity onPaused <<<
2018-12-27 08:45:44.255 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:45:44.255 4675-4675/com.ao.supermanager E/LoginActivity: onPause
2018-12-27 08:45:44.270 4675-4675/com.ao.supermanager W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@db294d7
2018-12-27 08:45:44.281 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onCreated <<<
2018-12-27 08:45:44.399 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onResumed <<<
2018-12-27 08:45:44.400 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:45:44.828 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:45:56.744 4675-4716/com.ao.supermanager W/CrashReport: [Upload] Use the back-up url at the last time: http://android.bugly.qq.com/rqd/async
2018-12-27 08:45:56.744 4675-4716/com.ao.supermanager D/CrashReport: [Upload] Send 1047 bytes
2018-12-27 08:45:56.744 4675-4716/com.ao.supermanager D/CrashReport: [Upload] Upload to http://android.bugly.qq.com/rqd/async?aid=bad5a6e5-bf41-422f-9b1a-9f1034ebba33 with cmd 840 (pid=4675 | tid=4716).
2018-12-27 08:45:56.745 4675-4716/com.ao.supermanager D/CrashReport: request: http://android.bugly.qq.com/rqd/async?aid=bad5a6e5-bf41-422f-9b1a-9f1034ebba33, send: 1047 (pid=4675 | tid=4716)
2018-12-27 08:45:56.752 4675-4716/com.ao.supermanager W/CrashReport: java.io.IOException: Cleartext HTTP traffic to android.bugly.qq.com not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.tencent.bugly.proguard.s.a(BUGLY:265)
        at com.tencent.bugly.proguard.s.a(BUGLY:114)
        at com.tencent.bugly.proguard.v.run(BUGLY:355)
        at com.tencent.bugly.proguard.u$1.run(BUGLY:723)
        at java.lang.Thread.run(Thread.java:764)
2018-12-27 08:45:56.752 4675-4716/com.ao.supermanager E/CrashReport: Failed to upload, please check your network.
2018-12-27 08:45:56.752 4675-4716/com.ao.supermanager D/CrashReport: Failed to execute post.
2018-12-27 08:45:56.752 4675-4716/com.ao.supermanager E/CrashReport: [Upload] Failed to upload(1): Failed to upload for no response!
2018-12-27 08:45:56.752 4675-4716/com.ao.supermanager E/CrashReport: [Upload] Failed to upload(1) userinfo: failed after many attempts
2018-12-27 08:45:56.753 4675-4716/com.ao.supermanager D/CrashReport: [UploadManager] Fail to init security context and clear local info (pid=4675 | tid=4716)
2018-12-27 08:45:56.753 4675-4716/com.ao.supermanager D/CrashReport: [UploadManager] Clear security context (pid=4675 | tid=4716)
2018-12-27 08:45:56.753 4675-4716/com.ao.supermanager D/CrashReport: [Util] Try to unlock file: security_info (pid=4675 | tid=4716)
2018-12-27 08:45:56.755 4675-4716/com.ao.supermanager D/CrashReport: [Util] Successfully unlocked file: security_info (pid=4675 | tid=4716)
2018-12-27 08:45:56.759 4675-4716/com.ao.supermanager D/CrashReport: [UploadManager] Local network consume: 3 KB
2018-12-27 08:45:56.761 4675-4716/com.ao.supermanager D/CrashReport: [Database] deleted t_lr data 1
2018-12-27 08:45:56.762 4675-4716/com.ao.supermanager D/CrashReport: [Database] insert t_lr success.
2018-12-27 08:45:56.762 4675-4716/com.ao.supermanager D/CrashReport: [UploadManager] Network total consume: 5 KB
2018-12-27 08:46:11.631 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onPaused <<<
2018-12-27 08:46:11.633 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:11.677 4675-4675/com.ao.supermanager W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@517c3aa
2018-12-27 08:46:11.694 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onCreated <<<
2018-12-27 08:46:11.716 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onCreate
2018-12-27 08:46:11.717 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:11.851 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:11.854 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:11.859 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onResumed <<<
2018-12-27 08:46:11.860 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:11.898 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:12.065 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:12.137 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:12.152 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:17.419 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onPaused <<<
2018-12-27 08:46:17.421 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:17.421 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onPause
2018-12-27 08:46:17.438 4675-4675/com.ao.supermanager W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cb75375
2018-12-27 08:46:17.452 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.AddOperationSelectDeviceActivity onCreated <<<
2018-12-27 08:46:17.466 4675-4675/com.ao.supermanager E/AddOperationSelectDeviceActivity: onCreate
2018-12-27 08:46:17.467 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:17.473 4675-4675/com.ao.supermanager I/chatty: uid=10086(com.ao.supermanager) identical 1 line
2018-12-27 08:46:17.475 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:17.481 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.AddOperationSelectDeviceActivity onResumed <<<
2018-12-27 08:46:17.482 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:17.617 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:19.570 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch: edgeFlag = 1
2018-12-27 08:46:19.571 4675-4675/com.ao.supermanager W/ao.supermanage: Accessing hidden field Landroid/view/WindowManagerImpl;->mGlobal:Landroid/view/WindowManagerGlobal; (light greylist, reflection)
2018-12-27 08:46:19.571 4675-4675/com.ao.supermanager W/ao.supermanage: Accessing hidden field Landroid/view/WindowManagerGlobal;->mViews:Ljava/util/ArrayList; (light greylist, reflection)
2018-12-27 08:46:19.571 4675-4675/com.ao.supermanager W/ao.supermanage: Accessing hidden field Landroid/view/WindowManagerGlobal;->mParams:Ljava/util/ArrayList; (light greylist, reflection)
2018-12-27 08:46:19.572 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 1 ;scrollPercent = 0.0
2018-12-27 08:46:19.842 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch:onScrollOverThreshold
2018-12-27 08:46:19.883 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 2 ;scrollPercent = 0.54670095
2018-12-27 08:46:20.369 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 0 ;scrollPercent = 1.008569
2018-12-27 08:46:20.384 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.AddOperationSelectDeviceActivity onPaused <<<
2018-12-27 08:46:20.386 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:20.386 4675-4675/com.ao.supermanager E/AddOperationSelectDeviceActivity: onPause
2018-12-27 08:46:20.420 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onRestart
2018-12-27 08:46:20.424 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onResumed <<<
2018-12-27 08:46:20.426 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:20.560 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:20.735 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.AddOperationSelectDeviceActivity onDestroyed <<<
2018-12-27 08:46:21.287 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch: edgeFlag = 1
2018-12-27 08:46:21.288 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 1 ;scrollPercent = 0.0
2018-12-27 08:46:21.572 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch:onScrollOverThreshold
2018-12-27 08:46:21.580 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 2 ;scrollPercent = 0.6623822
2018-12-27 08:46:22.078 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 0 ;scrollPercent = 0.0
2018-12-27 08:46:23.114 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch: edgeFlag = 1
2018-12-27 08:46:23.115 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 1 ;scrollPercent = 0.0
2018-12-27 08:46:23.387 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch:onScrollOverThreshold
2018-12-27 08:46:23.624 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 2 ;scrollPercent = 0.9091688
2018-12-27 08:46:24.060 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 0 ;scrollPercent = 1.008569
2018-12-27 08:46:24.063 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onPaused <<<
2018-12-27 08:46:24.065 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:24.066 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onPause
2018-12-27 08:46:24.099 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onResumed <<<
2018-12-27 08:46:24.100 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:24.147 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:24.227 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onDestroyed <<<
2018-12-27 08:46:26.232 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onPaused <<<
2018-12-27 08:46:26.233 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:26.261 4675-4675/com.ao.supermanager W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@11b3f0c
2018-12-27 08:46:26.272 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onCreated <<<
2018-12-27 08:46:26.277 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onCreate
2018-12-27 08:46:26.277 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:26.297 4675-4675/com.ao.supermanager I/chatty: uid=10086(com.ao.supermanager) identical 1 line
2018-12-27 08:46:26.301 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:26.305 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onResumed <<<
2018-12-27 08:46:26.306 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:26.313 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:26.390 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:26.424 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:26.431 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:28.891 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch: edgeFlag = 1
2018-12-27 08:46:28.891 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 1 ;scrollPercent = 0.0
2018-12-27 08:46:29.147 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch:onScrollOverThreshold
2018-12-27 08:46:29.211 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 2 ;scrollPercent = 0.9168809
2018-12-27 08:46:29.302 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 0 ;scrollPercent = 1.008569
2018-12-27 08:46:29.330 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onPaused <<<
2018-12-27 08:46:29.333 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:29.335 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onPause
2018-12-27 08:46:29.355 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onResumed <<<
2018-12-27 08:46:29.356 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:29.414 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:29.535 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onDestroyed <<<
2018-12-27 08:46:30.827 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onPaused <<<
2018-12-27 08:46:30.827 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:30.857 4675-4675/com.ao.supermanager W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@a9e0bbe
2018-12-27 08:46:30.864 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onCreated <<<
2018-12-27 08:46:30.870 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onCreate
2018-12-27 08:46:30.870 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:30.880 4675-4675/com.ao.supermanager I/chatty: uid=10086(com.ao.supermanager) identical 1 line
2018-12-27 08:46:30.882 4675-4675/com.ao.supermanager I/cgine: requestLayout mLayoutFrozen =false
2018-12-27 08:46:30.886 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onResumed <<<
2018-12-27 08:46:30.886 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:30.894 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:30.898 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:30.994 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:31.039 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:31.080 4675-4718/com.ao.supermanager I/chatty: uid=10086(com.ao.supermanager) RenderThread identical 2 lines
2018-12-27 08:46:31.114 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:31.494 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:32.730 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch: edgeFlag = 1
2018-12-27 08:46:32.730 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 1 ;scrollPercent = 0.0
2018-12-27 08:46:32.738 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:33.013 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch:onScrollOverThreshold
2018-12-27 08:46:33.029 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 2 ;scrollPercent = 0.83547556
2018-12-27 08:46:33.514 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 0 ;scrollPercent = 0.0
2018-12-27 08:46:34.675 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch: edgeFlag = 1
2018-12-27 08:46:34.675 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 1 ;scrollPercent = 0.0
2018-12-27 08:46:34.990 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onEdgeTouch:onScrollOverThreshold
2018-12-27 08:46:35.399 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 2 ;scrollPercent = 0.9168809
2018-12-27 08:46:35.817 4675-4675/com.ao.supermanager I/QMUIActivity: SwipeListener:onScrollStateChange: state = 0 ;scrollPercent = 1.008569
2018-12-27 08:46:35.831 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onPaused <<<
2018-12-27 08:46:35.831 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(false)
2018-12-27 08:46:35.831 4675-4675/com.ao.supermanager E/LeaveHomeModelActivity: onPause
2018-12-27 08:46:35.843 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.MainActivity onResumed <<<
2018-12-27 08:46:35.843 4675-4675/com.ao.supermanager I/CrashReport-Native: Set native info: isAppForeground(true)
2018-12-27 08:46:35.886 4675-4718/com.ao.supermanager D/EGL_emulation: eglMakeCurrent: 0xe8e6de60: ver 3 0 (tinfo 0xed8b1070)
2018-12-27 08:46:35.999 4675-4675/com.ao.supermanager D/CrashReport: >>> com.ao.supermanager.activity.LeaveHomeModelActivity onDestroyed <<<



![22](https://user-images.githubusercontent.com/8021798/50460877-c1b2e200-09b4-11e9-8758-1a3e20592c0a.gif)

**Comment by andrew203** [comment]
![1545877524657_video](https://user-images.githubusercontent.com/8021798/50463637-eb293900-09c7-11e9-9b1b-d2cd40492dcf.gif)

**Comment by cgspine** [comment]
@huaxi 这在 0.2.3 应该没问题了

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/50514678-c5d91f80-0ada-11e9-9134-7148848dedad.png)
@andrew203 在这里断点看看？像是这里获取前一个 actvitiy 的 view 失败了

**Comment by lihang1232** [comment]
这个闪屏问题修复了么

**Comment by cgspine** [comment]
0.6.2 及 2.x 的版本应该不会了

**Comment by lihang1232** [comment]
> 0.6.2 及 2.x 的版本应该不会了

使用的最新的2.0.0-alpha06 小部分手机侧滑返回来,闪了一下,好像是有一层半透明层执行了一个透明动画

**Comment by lihang1232** [comment]
![image](https://user-images.githubusercontent.com/29720163/80556913-be47c480-8a07-11ea-9b8b-bedce4f24db0.png)我把这个修改了下问题就好了 侧滑回来两个动画都不执行就不会闪屏了 拷贝了一部分类到自己项目改了下

**Comment by cgspine** [comment]
小部分手机包括哪些？
