### ISSUE TITLE
2. 配置主题

### ISSUE THREAD

**Issue by sinawangnan7** [QMUI/QMUI_Android#7]
2. 配置主题
把项目的 theme 的 parent 指向 QMUI.Compat 或 QMUI，至此，QMUI 可以正常工作。

想问下这个配置是什么？

尝试了一下这个style文件配置，运行程序直接崩溃...
    
    <style name="AppTheme" parent="QMUI">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

**Comment by chanthuang** [comment]
是否有程序崩溃的 Error 信息？

**Comment by sinawangnan7** [comment]
原因好像是Theme（主题）配置的有问题。
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.sina.wangnan7.myapplication, PID: 6917
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sina.wangnan7.myapplication/com.sina.wangnan7.myapplication.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2519)
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:161)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
                                                                                Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:359)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                   at com.sina.wangnan7.myapplication.MainActivity.onCreate(MainActivity.java:20)
                                                                                   at android.app.Activity.performCreate(Activity.java:6287)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2519) 
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:161) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5541) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by chanthuang** [comment]
把 `<style name="AppTheme" parent="QMUI">` 中的 `QMUI` 改成 `QMUI.Compat` 试试？因为你的 Activity 是继承自 AppCompatActivity，它要求 theme 是继承自 `Theme. AppCompat`的。

**Comment by sinawangnan7** [comment]
谢谢，和你说的原因一样，问题已解决...

**Comment by yanxinmiao** [comment]
AppTheme 的parent 必须是QMUI 或 QMUI.Compat吗 ？

如果我使用的是其他主题怎么办 ？
比如这个实现夜间模式要用到的 Theme.AppCompat.DayNight.NoActionBar

**Comment by sinawangnan7** [comment]
用自己的主题应该也没问题吧~只是使用QMUI的主题更符合他们的UI风格...

**Comment by chanthuang** [comment]
因为 QMUI 里的很多控件都依赖 theme，所以要求 AppTheme 的 parent 是 QMUI 或 QMUI.Compat。使用这2个 theme 本质上是为了给 QMUI 自定义的 attr 赋值。

如果你有使用自己主题的需求，目前可以使用你自己的主题，然后将 qmui_themes_compat.xml 文件中的 `<style name="QMUI.Compat"></style>` 里的 item 拷到自己的主题中，以保证依赖 theme 的控件能正常工作。

**Comment by yanxinmiao** [comment]
@chanthuang <style name="QMUI.Compat"></style>中的 item 不少啊 ，都是必需的吗
```
 <style name="QMUI.Compat" parent="AppConfigTheme.Compat">
        <item name="qmui_content_padding_horizontal">@dimen/qmui_content_padding_horizontal</item> <!-- 已废弃 -->
        <item name="qmui_content_spacing_horizontal">@dimen/qmui_content_spacing_horizontal</item>

        <!--**********************************************
        *                qmui common color               *
        **********************************************-->
        <item name="qmui_config_color_blue">@color/qmui_config_color_blue</item>
        <item name="qmui_config_color_red">@color/qmui_config_color_red</item>
        <item name="qmui_config_color_separator">@color/qmui_config_color_separator</item>
        <item name="qmui_config_color_separator_darken">@color/qmui_config_color_separator_darken</item>
        <item name="qmui_config_color_background">@color/qmui_config_color_background</item>
        <item name="qmui_config_color_background_pressed">@color/qmui_config_color_background_pressed</item>
        <item name="qmui_config_color_black">@color/qmui_config_color_black</item>
        <item name="qmui_config_color_link">@color/qmui_config_color_link</item>
        <item name="qmui_config_color_pressed">@color/qmui_config_color_pressed</item>

        <item name="qmui_config_color_gray_1">@color/qmui_config_color_gray_1</item>
        <item name="qmui_config_color_gray_2">@color/qmui_config_color_gray_2</item>
        <item name="qmui_config_color_gray_3">@color/qmui_config_color_gray_3</item>
        <item name="qmui_config_color_gray_4">@color/qmui_config_color_gray_4</item>
        <item name="qmui_config_color_gray_5">@color/qmui_config_color_gray_5</item>
        <item name="qmui_config_color_gray_6">@color/qmui_config_color_gray_6</item>
        <item name="qmui_config_color_gray_7">@color/qmui_config_color_gray_7</item>
        <item name="qmui_config_color_gray_8">@color/qmui_config_color_gray_8</item>
        <item name="qmui_config_color_gray_9">@color/qmui_config_color_gray_9</item>

        <item name="qmui_alpha_pressed">0.5</item>
        <item name="qmui_alpha_disabled">0.5</item>

        <!--**********************************************
        *                qmui dialog                     *
        **********************************************-->
        <item name="qmui_dialog_margin_horizontal">40dp</item>
        <item name="qmui_dialog_min_width">280dp</item>
        <item name="qmui_dialog_bg">@drawable/qmui_dialog_bg</item>
        <item name="qmui_dialog_margin_vertical">20dp</item>
        <item name="qmui_dialog_padding_horizontal">24dp</item>

        <!-- title -->
        <item name="qmui_dialog_title_text_color">?attr/qmui_config_color_black</item>
        <item name="qmui_dialog_title_margin_top">24dp</item>
        <item name="qmui_dialog_title_text_size">17sp</item>

        <!-- menu -->
        <item name="qmui_dialog_menu_item_check_icon_margin_horizontal">6dp</item>

        <!-- content -->
        <item name="qmui_dialog_content_padding_top">14dp</item>
        <item name="qmui_dialog_content_padding_top_when_no_title">27dp</item>
        <item name="qmui_dialog_content_padding_top_when_list">8dp</item>
        <item name="qmui_dialog_content_padding_bottom">28dp</item>
        <item name="qmui_dialog_content_padding_bottom_when_no_action">8dp</item>
        <item name="qmui_dialog_content_padding_bottom_when_action_block">16dp</item>
        <item name="qmui_dialog_content_message_text_size">16sp</item>
        <item name="qmui_dialog_content_list_item_height">48dp</item>
        <item name="qmui_dialog_content_list_item_text_size">15sp</item>
        <item name="qmui_dialog_content_list_item_bg">?attr/qmui_s_list_item_bg_with_border_none</item>
        <item name="qmui_dialog_confirm_content_padding_top">28dp</item>
        <item name="qmui_dialog_confirm_content_padding_bottom">22dp</item>
        <item name="qmui_dialog_edit_content_padding_top">28dp</item>
        <item name="qmui_dialog_edit_content_padding_bottom">31dp</item>
        <item name="qmui_dialog_block_content_text_size">14sp</item>
        <item name="qmui_dialog_menu_item_text_color">?attr/qmui_config_color_black</item>

        <!-- action -->
        <item name="qmui_dialog_action_container_margin_bottom">12dp</item>
        <item name="qmui_dialog_action_container_margin_horizontal">12dp</item>
        <item name="qmui_dialog_action_button_min_width">64dp</item>
        <item name="qmui_dialog_action_button_height">36dp</item>
        <item name="qmui_dialog_action_button_margin_left">8dp</item>
        <item name="qmui_dialog_action_drawable_padding">6dp</item>
        <item name="qmui_dialog_action_button_text_size">14sp</item>
        <item name="qmui_dialog_action_button_padding_horizontal">12dp</item>

        <item name="qmui_dialog_action_block_container_margin_bottom">12dp</item>
        <item name="qmui_dialog_action_block_btn_height">36dp</item>

        <item name="qmui_dialog_action_text_negative_color">@color/qmui_dialog_action_text_negative_color</item>
        <item name="qmui_dialog_action_text_color">@color/qmui_dialog_action_text_color</item>
        <item name="qmui_dialog_action_btn_bg">@drawable/qmui_dialog_action_btn_bg</item>
        <item name="qmui_dialog_action_block_btn_bg">?attr/qmui_s_list_item_bg_with_border_none</item>

        <!-- tip -->
        <item name="qmui_tip_dialog_bg">@drawable/qmui_tip_dialog_bg</item>
        <item name="qmui_tip_dialog_min_width">120dp</item>
        <item name="qmui_tip_dialog_min_height">56dp</item>
        <item name="qmui_tip_dialog_margin_horizontal">?attr/qmui_content_spacing_horizontal</item>
        <item name="qmui_tip_dialog_padding_vertical">12dp</item>
        <item name="qmui_tip_dialog_padding_horizontal">?attr/qmui_content_padding_horizontal</item>
        <!--**********************************************
        *             qmui list item bg                  *
        **********************************************-->
        <item name="qmui_list_item_height">@dimen/qmui_list_item_height</item>
        <item name="qmui_list_item_height_higher">@dimen/qmui_list_item_height_higher</item>

        <item name="qmui_list_item_bg_with_border_bottom">@drawable/qmui_list_item_bg_with_border_bottom</item>
        <item name="qmui_list_item_bg_with_border_bottom_pressed">@drawable/qmui_list_item_bg_with_border_bottom_pressed</item>
        <item name="qmui_list_item_bg_with_border_bottom_inset_left">@drawable/qmui_list_item_bg_with_border_bottom_inset_left</item>
        <item name="qmui_list_item_bg_with_border_bottom_inset_left_pressed">@drawable/qmui_list_item_bg_with_border_bottom_inset_left_pressed</item>
        <item name="qmui_list_item_bg_with_border_top">@drawable/qmui_list_item_bg_with_border_top</item>
        <item name="qmui_list_item_bg_with_border_top_pressed">@drawable/qmui_list_item_bg_with_border_top_pressed</item>
        <item name="qmui_list_item_bg_with_border_top_inset_left">@drawable/qmui_list_item_bg_with_border_top_inset_left</item>
        <item name="qmui_list_item_bg_with_border_top_inset_left_pressed">@drawable/qmui_list_item_bg_with_border_top_inset_left_pressed</item>
        <item name="qmui_list_item_bg_with_border_double">@drawable/qmui_list_item_bg_with_double_border</item>
        <item name="qmui_list_item_bg_with_border_double_pressed">@drawable/qmui_list_item_bg_with_double_border_pressed</item>

        <item name="qmui_s_list_item_bg_with_border_bottom">@drawable/qmui_s_list_item_bg_with_border_bottom</item>
        <item name="qmui_s_list_item_bg_with_border_bottom_inset">@drawable/qmui_s_list_item_bg_with_border_bottom_inset</item>
        <item name="qmui_s_list_item_bg_with_border_bottom_inset_left">@drawable/qmui_s_list_item_bg_with_border_bottom_inset_left</item>
        <item name="qmui_s_list_item_bg_with_border_top">@drawable/qmui_s_list_item_bg_with_border_top</item>
        <item name="qmui_s_list_item_bg_with_border_top_inset_left">@drawable/qmui_s_list_item_bg_with_border_top_inset_left</item>
        <item name="qmui_s_list_item_bg_with_border_double">@drawable/qmui_s_list_item_bg_with_border_double</item>
        <item name="qmui_s_list_item_bg_with_border_none">@drawable/qmui_s_list_item_bg_with_border_none</item>

        <!--**********************************************
        *             qmui drawable                      *
        ***********************************************-->
        <item name="qmui_s_checkbox">@drawable/qmui_s_checkbox</item>
        <item name="qmui_icon_check_mark">@drawable/qmui_icon_checkmark</item>

        <!--**********************************************
        *                   qmui btn                     *
        ***********************************************-->
        <item name="qmui_round_btn_text_size">@dimen/qmui_btn_text_size</item>
        <item name="qmui_round_btn_border_width">@dimen/qmui_btn_border_width</item>
        <item name="qmui_round_btn_bg_color">@color/qmui_btn_blue_bg</item>
        <item name="qmui_round_btn_border_color">@color/qmui_btn_blue_border</item>
        <item name="qmui_round_btn_text_color">@color/qmui_btn_blue_text</item>

        <!--**********************************************
        *                  qmui topbar                   *
        ***********************************************-->
        <item name="qmui_topbar_height">56dp</item>
        <item name="qmui_topbar_title_color">@color/qmui_config_color_gray_1</item>
        <item name="qmui_topbar_title_text_size">17sp</item>
        <item name="qmui_topbar_title_text_size_with_subtitle">16sp</item>
        <item name="qmui_topbar_title_margin_horizontal_when_no_btn_aside">@dimen/qmui_content_padding_horizontal</item>
        <item name="qmui_topbar_subtitle_text_size" >11sp</item>
        <item name="qmui_topbar_subtitle_color">@color/qmui_config_color_gray_1</item>
        <item name="qmui_topbar_image_btn_width">48dp</item>
        <item name="qmui_topbar_image_btn_height">48dp</item>
        <item name="qmui_topbar_text_btn_padding_horizontal">12dp</item>
        <item name="qmui_topbar_text_btn_color_state_list">@color/qmui_topbar_text_color</item>
        <item name="qmui_topbar_text_btn_text_size">16sp</item>

        <!--**********************************************
        *                 qmui bottom sheet              *
        ***********************************************-->
        <item name="qmui_bottom_sheet_title_height">56dp</item>
        <item name="qmui_bottom_sheet_title_appearance">@style/QMUITextAppearance.Title.Gray</item>
        <item name="qmui_bottom_sheet_title_bg">?attr/qmui_list_item_bg_with_border_bottom</item>

        <item name="qmui_bottom_sheet_list_item_padding_horizontal">?attr/qmui_content_padding_horizontal</item>
        <item name="qmui_bottom_sheet_list_item_height">56dp</item>
        <item name="qmui_bottom_sheet_list_item_mark_margin_left">12dp</item>
        <item name="qmui_bottom_sheet_list_item_tip_point_margin_left">4dp</item>
        <item name="qmui_bottom_sheet_list_item_text_appearance">@style/QMUITextAppearance.ListItem</item>
        <item name="qmui_bottom_sheet_list_item_bg">?attr/qmui_s_list_item_bg_with_border_bottom</item>
        <item name="qmui_bottom_sheet_list_item_icon_size">22dp</item>
        <item name="qmui_bottom_sheet_list_item_icon_margin_right">12dp</item>

        <item name="qmui_bottom_sheet_grid_padding_vertical">12dp</item>
        <item name="qmui_bottom_sheet_grid_line_padding_horizontal">12dp</item>
        <item name="qmui_bottom_sheet_grid_line_vertical_space">0dp</item>
        <item name="qmui_bottom_sheet_grid_item_mini_width">84dp</item>
        <item name="qmui_bottom_sheet_grid_item_icon_size">56dp</item>
        <item name="qmui_bottom_sheet_grid_item_text_appearance">@style/QMUITextAppearance.GridItem.Small</item>

        <item name="qmui_bottom_sheet_button_height">56dp</item>
        <item name="qmui_bottom_sheet_button_text_size">15sp</item>
        <item name="qmui_bottom_sheet_button_text_color">@color/qmui_config_color_gray_2</item>
        <item name="qmui_bottom_sheet_button_text_background">@drawable/qmui_s_list_item_bg_with_border_top</item>

        <!--**********************************************
        *                 qmui common list item          *
        ***********************************************-->
        <item name="qmui_common_list_item_chevron">@drawable/icon_chevron</item>

        <!--**********************************************
        *               qmui loading view                *
        ***********************************************-->
        <item name="qmui_loading_size">20dp</item>
        <item name="qmui_loading_color">@color/qmui_config_color_gray_5</item>

        <!--**********************************************
        *                   qmui popup                   *
        ***********************************************-->
        <item name="qmui_popup_bg">@drawable/qmui_popup_bg</item>
        <item name="qmui_popup_arrow_down">@drawable/qmui_popup_arrow_down</item>
        <item name="qmui_popup_arrow_up">@drawable/qmui_popup_arrow_up</item>
        <item name="qmui_popup_arrow_up_margin_top">13dp</item>
        <item name="qmui_popup_arrow_down_margin_bottom">13dp</item>

        <!--**********************************************
        *                  qmui tabSegment               *
        ***********************************************-->
        <item name="qmui_tab_sign_count_view">@style/qmui_tab_sign_count_view</item>
        <item name="qmui_tab_sign_count_view_minSize">@dimen/qmui_tab_sign_count_view_minSize</item>
        <item name="qmui_tab_sign_count_view_minSize_with_text">@dimen/qmui_tab_sign_count_view_minSize_with_text</item>
        <item name="qmui_tab_sign_count_view_bg">@drawable/qmui_sign_count_view_bg</item>
        <item name="qmui_tab_sign_count_view_padding_horizontal">4dp</item>

        <!--**********************************************
        *               qmui 提供的控件样式                *
        ***********************************************-->
        <item name="QMUIButtonStyle">@style/QMUI.RoundButton</item>
        <item name="QMUITabSegmentStyle">@style/QMUI.TabSegment</item>
        <item name="QMUICommonListItemViewStyle">@style/QMUI.CommonListItemView</item>
        <item name="QMUIGroupListSectionViewStyle">@style/QMUI.GroupListSectionView</item>
        <item name="QMUITopBarStyle">@style/QMUI.TopBar</item>

        <item name="QMUITipPointStyle">@style/QMUI.TipPoint</item>
        <item name="QMUITipNewStyle">@style/QMUI.TipNew</item>

        <item name="QMUILoadingStyle">@style/QMUI.Loading</item>
        <item name="QMUIPullRefreshLayoutStyle">@style/QMUI.PullRefreshLayout</item>
        <item name="QMUIRadiusImageViewStyle">@style/QMUI.RadiusImageView</item>
        <item name="QMUIQQFaceStyle">@style/QMUI.QQFaceView</item>
    </style>
```

**Comment by cgspine** [comment]
基本是必须的吧，除非你确定某个组件永远不会用到， 那么你就可以不用拷贝相关组件的配置。但建议还是全部加上吧，相对于系统提供的，也不算很多。
