### ISSUE TITLE
 Caused by: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by yinhe-zeng** [QMUI/QMUI_Android#73]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qmuiteam.qmui.widget.textview.QMUISpanTouchFixTextView" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/xxx.xxx.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/xxx.xxxx.xxx-2/lib/arm, /data/app/xxx.xxx.xxx-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

**Comment by cgspine** [comment]
使用了mutidex 并使用了instant run？

**Comment by yinhe-zeng** [comment]
使用了multidex，没有使用instant run

**Comment by cgspine** [comment]
release包吗？代码混淆？

**Comment by cgspine** [comment]
https://stackoverflow.com/questions/41382641/multidex-issue-java-lang-classnotfoundexception-didnt-find-class-on-path-dex

这里有一个ClassNotFoundException的issue，重启电脑.......

**Comment by yinhe-zeng** [comment]
没找到解决问题的方法，附上详细的堆栈：
java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.xxx.xxx/xxx.xxx.xxx.xxxActivity}: android.view.InflateException: Binary XML file line #470: Binary XML file line #470: Error inflating class com.qmuiteam.qmui.widget.textview.QMUISpanTouchFixTextView
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2451)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                    Caused by: android.view.InflateException: Binary XML file line #470: Binary XML file line #470: Error inflating class com.qmuiteam.qmui.widget.textview.QMUISpanTouchFixTextView
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:558)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:434)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)
                                                       at android.app.Activity.setContentView(Activity.java:2219)
                                                       at xxx.xxx.xxx.xxxActivity.onCreate(xxxActivity.java:180)
                                                       at android.app.Activity.performCreate(Activity.java:6367)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                    Caused by: android.view.InflateException: Binary XML file line #470: Error inflating class com.qmuiteam.qmui.widget.textview.QMUISpanTouchFixTextView
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:795)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:857)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:857)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:434) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420) 
                                                       at android.app.Activity.setContentView(Activity.java:2219) 
                                                       at xxx.xxx.xxx.xxxActivity.onCreate(xxxActivity.java:180) 
                                                       at android.app.Activity.performCreate(Activity.java:6367) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qmuiteam.qmui.widget.textview.QMUISpanTouchFixTextView" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/xxx.xxx.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/xxx.xxx.xxx-2/lib/arm, /data/app/xxx.xxx.xxx-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:602)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:783)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:854) 
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:857) 
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:857) 
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:434) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420) 
                                                       at android.app.Activity.setContentView(Activity.java:2219) 
                                                       at xxx.xxx.xxx.xxxActivity.onCreate(xxxActivity.java:180) 
                                                       at android.app.Activity.performCreate(Activity.java:6367) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                   	Suppressed: java.lang.ClassNotFoundException: com.qmuiteam.qmui.widget.textview.QMUISpanTouchFixTextView
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 28 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by cgspine** [comment]
https://github.com/TangXiaoLv/Android-Easy-MultiDex/issues/7
堆栈很像这上面这个
