### ISSUE TITLE
请问在Adapter里面怎么使用QMUIDialog

### ISSUE THREAD

**Issue by ixxxxxx** [QMUI/QMUI_Android#92]
### 运行环境 ###

- [x] 设备型号：`Nexus 6P`
- [x] 设备系统版本：`Android 8.0`
- [x] Gradle 版本：`3.0.0`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
你好，我在做一个类似微博的消息动态，用`RecyclerView`实现的，然后每个item里面如果是自己发送的话会有删除按钮。当点击删除时候，想让他先弹出一个`QMUIDialog`。然后我在Adapter里面的`onBindViewHolder`添加了如下代码

```
        holder.feedDeleteBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                new QMUIDialog.MessageDialogBuilder(MyApplication.getAppContext())
                        .setTitle("")
                        .setMessage("Are you confirm to delete this feed?")
                        .addAction("Cancel", new QMUIDialogAction.ActionListener() {
                            @Override
                            public void onClick(QMUIDialog dialog, int index) {
                                dialog.dismiss();
                            }
                        })
                        .addAction(0, "Delete", QMUIDialogAction.ACTION_PROP_NEGATIVE, new QMUIDialogAction.ActionListener() {
                            @Override
                            public void onClick(QMUIDialog dialog, int index) {
                                //TODO:删除自己所发的feed
                                dialog.dismiss();
                            }
                        })
                        .show();
            }
        });
```
然后我点击这个删除按钮的话，程序会崩溃。初步判断是`new QMUIDialog.MessageDialogBuilder(MyApplication.getAppContext())`这里用的context是我自定义的一个通用的context。
请问在一个Adapter里面怎么弹出一个`QMUIDialog`？
#### 异常日志（堆栈） ####
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.arcadefire.arcadefire, PID: 24606
                  android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
                  Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
                  Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                      at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:239)
                      at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:226)
                      at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.show(QMUIDialogBuilder.java:215)
                      at com.loveoversea.arcadefire.Adapter.FeedAdapter$1.onClick(FeedAdapter.java:120)
                      at android.view.View.performClick(View.java:6256)
                      at android.view.View$PerformClick.run(View.java:24697)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f03019f a=2}
                      at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
                      at android.view.View.<init>(View.java:4730)
                      at android.view.ViewGroup.<init>(ViewGroup.java:597)
                      at android.widget.LinearLayout.<init>(LinearLayout.java:234)
                      at android.widget.LinearLayout.<init>(LinearLayout.java:230)
                      at android.widget.LinearLayout.<init>(LinearLayout.java:226)
                      at java.lang.reflect.Constructor.newInstance0(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                      at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:239) 
                      at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:226) 
                      at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.show(QMUIDialogBuilder.java:215) 
                      at com.loveoversea.arcadefire.Adapter.FeedAdapter$1.onClick(FeedAdapter.java:120) 
                      at android.view.View.performClick(View.java:6256) 
                      at android.view.View$PerformClick.run(View.java:24697) 
                      at android.os.Handler.handleCallback(Handler.java:789) 
                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by ixxxxxx** [comment]
使用传递过来的context就好了。
`QMUIDialog.MessageDialogBuilder(context)`
